
import {
  UploadCloud,
  FileText,
  Share2,
  ShieldAlert,
  Settings,
  LayoutDashboard,
  BookOpen,
  GitFork,
  Zap,
  Eye,
  FileJson,
  Globe,
  Loader2,
  ChevronRight,
  ChevronDown,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Info,
  ExternalLink,
  Server,
  Replace,
  PlusCircle,
  Trash2,
  Network,
  ArrowRightCircle, 
  Edit3,
  Edit,
  Home,
  ListChecks,
  FilePlus2,
  FileOutput,
  Activity,
  HeartPulse,
  ShieldCheck,
  Gavel,
  LogIn,
  LogOut,
  Cpu,
  MemoryStick,
  GaugeCircle,
  AlertOctagon,
  SlidersHorizontal,
  ClipboardList,
  Lightbulb,
  LineChart,
  PauseCircle,
  PlayCircle,
  RefreshCw,
  Maximize,
  Palette, // For Pattern Intelligence or general design
  Search,
  Radar, // For Live API Discovery
  TrendingUp, // For Predictive Monitoring
  Webhook, // Alternative for discovery or events
  LocateFixed, // Alternative for discovery
  BrainCircuit, // Alternative for predictive/AI
  Gauge, // Alternative for monitoring/predictive
  User, 
  ShoppingCart, 
  ArrowDown,
  Database,
  Shield,
  ImageIcon,
  KeyRound, // For OAuth
  List, // For Pagination
  ArrowLeft, // For Content Negotiation
  ServerCog, // For Admin Settings
  Link2, // For Admin Integrations
  Rocket, // For Getting Started
  Layers, // For API Discovery (alternative)
  Blend, // For Pattern Intelligence (alternative)
  BarChartHorizontal, // For Analytics
  Landmark // For Governance
} from 'lucide-react';

export const Icons = {
  UploadCloud,
  FileText,
  Share2,
  ShieldAlert,
  Settings,
  LayoutDashboard,
  BookOpen,
  GitFork,
  Zap,
  Eye,
  FileJson,
  Globe,
  Loader: Loader2,
  ChevronRight,
  ChevronDown,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Info,
  ExternalLink,
  Server,
  HttpReplace: Replace,
  HttpPost: PlusCircle,
  HttpDelete: Trash2,
  HttpPatch: Edit,
  HttpGet: ArrowRightCircle,
  ArrowRightCircle, 
  Network,
  Home,
  ListChecks,
  FilePlus2,
  FileOutput,
  Activity,
  HeartPulse,
  ShieldCheck,
  Gavel,
  LogIn,
  LogOut,
  Cpu,
  MemoryStick,
  GaugeCircle,
  AlertOctagon,
  SlidersHorizontal,
  ClipboardList,
  Lightbulb,
  LineChart,
  PauseCircle,
  PlayCircle,
  RefreshCw,
  Maximize,
  Palette, 
  Search,
  Radar,
  TrendingUp,
  Webhook,
  LocateFixed,
  BrainCircuit,
  Gauge,
  User,
  ShoppingCart,
  ArrowDown,
  Database,
  Shield,
  ImageIcon,
  KeyRound,
  List,
  ArrowLeft,
  ServerCog,
  Link2,
  Rocket,
  Layers,
  Blend,
  BarChartHorizontal,
  Landmark
};

export const ApiMethodIcons: Record<string, React.ElementType> = {
  get: Icons.HttpGet,
  post: Icons.HttpPost,
  put: Icons.HttpReplace,
  delete: Icons.HttpDelete,
  patch: Icons.HttpPatch,
  options: Icons.Settings,
  head: Icons.Eye,
  trace: Icons.GitFork,
};
